export const EXPERIENCE = [
  {
    id: 1,
    role: "Software Engineer",
    company: "Smart Applications International",
    period: "June 2025 - Present",
    description: [
      "Developed and maintained frontend features for the Smart Insure platform using Angular, supporting core insurance workflows such as product configuration, quotations, and role-based access control",
      "Built and enhanced reusable UI components to improve usability, consistency, and delivery speed across the application",
      "Collaborated with backend, QA, and product teams to integrate APIs, troubleshoot issues, and deliver reliable, user-focused solutions",
      "Refactored existing components and optimised frontend performance, improving application stability and maintainability",
      "Ensured adherence to coding standards, data security practices, and version control processes through active participation in code reviews",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "JavaScript",
      "MySQL",
      "SQL Server",
      "Git",
      "Docker",
    ],
  },
  {
    id: 2,
    role: "Softawre Engineer",
    company: "Revenue Catalyst",
    period: "February 2024 - May 2025",
    description: [
      "RevCat v2: Implemented and optimized the second version of the RevCat platform using Next.js and Tailwind CSS",
      "Built an administrative interface to manage platform tenants, streamlining user onboarding and account operations",
      "Contributed to Covecta (UK-based Startup): Developed front-end features and enhancements for AI banking helpers",
      "Leveraged modern JavaScript/TypeScript practices across all projects",
      "Ensured responsive UI/UX and maintained clean, maintainable code",
      "Knowledge Base Development: Created a system to collect and organize company information for the RevCat platform",
      "Assisted in feature implementation and platform enhancements",
      "Gained hands-on experience with Angular and Angular Material",
      "Strengthened proficiency in front-end best practices and component-driven design",
      "Developed responsive UI/UX implementations",
    ],
    technologies: [
      "Angular",
      "Angular Material",
      "Javascript",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "React",
    ],
  },
  {
    id: 3,
    role: "Software Engineer Intern",
    company: "theJitu",
    period: "April 2023 - June 2023",
    description: [
      "Gained hands-on experience with full-stack development technologies",
      "Contributed to development and maintenance of multiple projects",
      "Collaborated on designing and implementing dynamic web applications",
      "Improved application functionality and user experience",
      "Worked with databases, writing complex SQL queries for data management",
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "Angular",
      "Express.js",
      "Node.js",
      "SQL",
    ],
  },
];

export const PROJECTS = [
  {
    id: 1,
    title: "Note Taking App",
    description:
      "A modern note-taking application with rich text support and markdown compatibility",
    technologies: ["React", "TypeScript", "Tailwind CSS"],
    githubUrl: "https://github.com/sanmdambuki/note-taking-app",
    demoUrl: "#",
    image: "/images/projects/note-app.jpg",
    features: [
      "Rich text editing capabilities",
      "Markdown support",
      "Responsive design",
      "Local storage persistence",
    ],
  },
  {
    id: 2,
    title: "Online Shoe Shop",
    description:
      "An e-commerce web application for browsing, selecting, and purchasing shoes with a clean and responsive user interface.",
    technologies: ["Angular", "TypeScript", "CSS", "REST API"],
    githubUrl: "https://github.com/samndambuki/online-shoe-shop",
    demoUrl: "#",
    image: "/images/projects/shoe-shop.jpg",
    features: [
      "Product listing and detailed product views",
      "Shopping cart functionality",
      "Responsive UI for multiple devices",
      "Dynamic data rendering from APIs",
    ],
  },
  {
    id: 3,
    title: "Stack Overflow Clone",
    description:
      "A Q&A platform inspired by Stack Overflow, enabling users to ask questions, post answers, and interact with technical content.",
    technologies: ["Angular", "TypeScript", "Node.js", "SQL"],
    githubUrl: "https://github.com/samndambuki/stack-overflow.git",
    demoUrl: "#",
    image: "/images/projects/stack-overflow-clone.jpg",
    features: [
      "Question and answer posting",
      "User interaction through comments and votes",
      "Structured data handling with SQL",
      "Clean, component-based frontend architecture",
    ],
  },
  {
    id: 4,
    title: "Online Code Compiler",
    description:
      "A web-based code compiler that allows users to write, compile, and execute code in multiple programming languages through a browser interface.",
    technologies: [
      "Angular",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Docker",
      "REST API",
    ],
    githubUrl: [
      "https://github.com/samndambuki/code-zap-frontend",
      "https://github.com/samndambuki/code-zap-api",
    ],
    demoUrl: "#",
    image: "/images/projects/code-compiler.jpg",
    features: [
      "Online code editor with execution support",
      "Backend API for code compilation and execution",
      "Docker-based containerization for isolated runtimes",
      "Frontend-backend integration via REST APIs",
    ],
  },
  {
    id: 5,
    title: "Movie App",
    description:
      "Browse popular movies with details, ratings, and search functionality",
    technologies: ["React", "JavaScript"],
    githubUrl: "https://github.com/sanmdambuki/movie-app",
    demoUrl: "#",
    image: "/images/projects/movie-app.jpg",
    features: [
      "Movie discovery interface",
      "Detailed movie information",
      "Search functionality",
      "Rating display",
    ],
  },
  {
    id: 6,
    title: "Social Network Wall",
    description: "A social media-style wall application with user interactions",
    technologies: ["Angular", "Angular Material", "json-server"],
    githubUrl: "https://github.com/sanmdambuki/Social-Network-Wall",
    demoUrl: "#",
    image: "/images/projects/social-wall.jpg",
    features: [
      "Post creation and display",
      "User authentication simulation",
      "Real-time updates",
      "Material Design interface",
    ],
  },
  {
    id: 7,
    title: "Eshop",
    description:
      "An e-commerce platform with product listings and cart functionality",
    technologies: ["React", "JavaScript"],
    githubUrl: "https://github.com/sanmdambuki/Eshop",
    demoUrl: "#",
    image: "/images/projects/eshop.jpg",
    features: [
      "Product catalog",
      "Shopping cart system",
      "Category filtering",
      "Responsive storefront",
    ],
  },
  {
    id: 8,
    title: "Recipe Finder Web App",
    description: "Application for discovering and saving cooking recipes",
    technologies: ["Angular", "json-server", "Tailwind CSS"],
    githubUrl: "https://github.com/sanmdambuki/recipe-finder-app",
    demoUrl: "#",
    image: "/images/projects/recipe-app.jpg",
    features: [
      "Recipe search functionality",
      "Favorite recipes storage",
      "Detailed cooking instructions",
      "Ingredient lists",
    ],
  },
];

export const SKILLS = [
  { name: "JavaScript", level: 90 },
  { name: "TypeScript", level: 85 },
  { name: "Angular", level: 80 },
  { name: "React", level: 85 },
  { name: "Next.js", level: 75 },
  { name: "Tailwind CSS", level: 88 },
  { name: "Angular Material", level: 78 },
  { name: "Node.js", level: 70 },
  { name: "HTML/CSS", level: 95 },
];
